name: Processing pull requests
on: 
  pull_request:
    types: [closed]

jobs:   
  communicate-on-pull-request-merged:
    name: communicate on pull request merged
    runs-on: ubuntu-latest    
    steps:
      - name: Git checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@master
        with:
          ref: refs/heads/master
      
      - name: Communicate on PR merged
        if: github.event.pull_request.merged
        uses: fastlane/github-actions/communicate-on-pull-request-merged@latest
        with:
          repo-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          pr-comment: "Hey @${{ github.event.pull_request.user.login }} :wave:\n\n
            Thank you for your contribution to _fastlane_ and congrats on getting this pull request merged :tada:\n
            The code change now lives in the `master` branch, however it wasn't released to [RubyGems](https://rubygems.org/gems/fastlane) yet.\n
            We usually ship about once a week, and your PR will be included in the next one.\n\n
            Please let us know if this change requires an immediate release by adding a comment here :+1:\n
            We'll notify you once we shipped a new release with your changes :rocket:"
          pr-label-to-add: 'status: included-in-next-release'
          pr-label-to-remove: 'status: needs-attention'
